### ISSUE TITLE
openapi-router : PATCH as router feature ?

### ISSUE THREAD

**Issue by ben1lam8** [builder-group/community#84]
Hi here !

First of all : great job. thanks for this promising tool 👍🏻 

Then : Did you plan to wrap Express' router PATCH as a feature ? When ? 
Get, post, put and delete are not enough, in our case.

We are prototyping a new API with openapits and this router, but without this HTTP method, it could end up in a no-go and go back to vanilla Express.

**Comment by jpx15** [comment]
Yeah, I was wondering the same thing. This is an excellent library but this seems an odd oversight.

**Comment by seddonm1** [comment]
I think this is enough: https://github.com/builder-group/community/pull/85

**Comment by bennobuilder** [comment]
Sorry for the late reply. Had my notification settings misconfigured and thus missed this issue 😅

Good news: The `PATCH` method has been added to both Hono and Express 🎉 Huge thanks to @seddonm1 

Feel free to give it a try and let me know if you have any feedback (also in general, like DX, etc.) 🙌
